version: '3'


services:
  mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-mfl_interface_db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-DodgerMXT123}
      MYSQL_USER: ${MYSQL_USER:-his}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-DodgerMXT123}
    healthcheck:
      test: "exit 0"

  web:
    build: .
    image: dwh_his_interface
    volumes:
      - .:/project    
    depends_on:
      - mysql
    ports:
      - "8100:8000"
    environment:
      DB_DATABASE: ${MYSQL_DB:-mfl_interface_db}
      DB_HOST: dwh-his_mysql_1
      DB_USERNAME: ${MYSQL_USER:-his}
      DB_PASSWORD: ${MYSQL_PASSWORD:-DodgerMXT123}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/"]
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python manage.py makemigrations --merge
        sleep 10
        python manage.py migrate --noinput
        sleep 10
        python manage.py loaddata secondset.json
        sleep 40
        python manage.py runserver 0.0.0.0:8000      
